on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legaci-peer-deps
      - name: Build Storybook
        run: npm run sb:build
      - name: install playwright
        run: npm install playwright@latest --with-deps
      - name: start test playwright
        run: npx playwright test
      - name: update docker
        run: docker pull mcr.microsoft.com/playwright:v1.35.0-jammy
      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v2.11.0