
# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     name: Lost Pixel

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 19.x
#           cache: "npm"

#       - name: Install dependencies
#         run: npm ci
    
#       - name: Build Storybook
#         run: npm run sb:build 

#       - name: Lost Pixel
#         uses: lost-pixel/lost-pixel@v3.8.0
#         env:
#           LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
          
